"""Export the three tables the ask layer needs into a SQL file for Cloudflare D1.

D1 is SQLite, so this is close to a straight dump: parcels, owners, and
violations, with the same schema and indexes the local database uses, plus
the ratelimit table the Worker writes to. No BEGIN/COMMIT (D1 rejects
explicit transactions in imported files).

Run:    python3 pipeline/export_d1.py           # writes worker/d1_import.sql
Check:  python3 pipeline/export_d1.py --check   # loads the dump into a fresh
                                                # in-memory db and compares it
                                                # row-for-row against the source
"""
import os
import sqlite3
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DB = os.path.join(ROOT, "data", "empty_homes.db")
OUT = os.path.join(ROOT, "worker", "d1_import.sql")
TABLES = ["parcels", "owners", "violations"]
BATCH = 50  # rows per INSERT statement

SCHEMA = """
DROP TABLE IF EXISTS parcels;
DROP TABLE IF EXISTS owners;
DROP TABLE IF EXISTS violations;
CREATE TABLE parcels (
  opa_id TEXT PRIMARY KEY,
  address TEXT, zip TEXT, council_district TEXT,
  lat REAL, lon REAL,
  vacant_flag TEXT, vacant_rank REAL, bldg_desc TEXT,
  owner_raw TEXT,
  owner_id INTEGER,
  market_value INTEGER, sale_date TEXT, sale_price INTEGER, category TEXT,
  mailing_addr TEXT,
  delinquent INTEGER DEFAULT 0,
  years_owed INTEGER, oldest_year_owed INTEGER, total_due REAL,
  sheriff_sale TEXT, payment_agreement TEXT,
  open_violations INTEGER DEFAULT 0,
  score INTEGER DEFAULT 0
);
CREATE TABLE owners (
  id INTEGER PRIMARY KEY,
  canonical_name TEXT UNIQUE,
  kind TEXT,
  cluster_id INTEGER,
  parcel_count INTEGER,
  total_due REAL,
  avg_years_owed REAL
);
CREATE TABLE violations (opa_id TEXT, title TEXT, date TEXT);
CREATE INDEX idx_parcels_zip ON parcels(zip);
CREATE INDEX idx_parcels_owner ON parcels(owner_id);
CREATE INDEX idx_violations_opa ON violations(opa_id);
CREATE TABLE IF NOT EXISTS ratelimit (key TEXT PRIMARY KEY, count INTEGER);
"""


def sql_literal(v):
    if v is None:
        return "NULL"
    if isinstance(v, (int, float)):
        return repr(v)
    return "'%s'" % str(v).replace("'", "''")


def dump():
    con = sqlite3.connect("file:%s?mode=ro" % DB, uri=True)
    with open(OUT, "w") as f:
        f.write("-- Generated by pipeline/export_d1.py. Do not edit.\n")
        f.write(SCHEMA)
        for table in TABLES:
            cols = [r[1] for r in con.execute("PRAGMA table_info(%s)" % table)]
            rows = con.execute("SELECT %s FROM %s" % (", ".join(cols), table))
            batch = []
            for row in rows:
                batch.append("(%s)" % ", ".join(sql_literal(v) for v in row))
                if len(batch) == BATCH:
                    f.write("INSERT INTO %s (%s) VALUES\n%s;\n"
                            % (table, ", ".join(cols), ",\n".join(batch)))
                    batch = []
            if batch:
                f.write("INSERT INTO %s (%s) VALUES\n%s;\n"
                        % (table, ", ".join(cols), ",\n".join(batch)))
    con.close()
    size = os.path.getsize(OUT)
    print("wrote %s (%.1f MB)" % (OUT, size / 1e6))


def check():
    src = sqlite3.connect("file:%s?mode=ro" % DB, uri=True)
    dst = sqlite3.connect(":memory:")
    dst.executescript(open(OUT).read())
    for table in TABLES:
        a = src.execute("SELECT count(*) FROM %s" % table).fetchone()[0]
        b = dst.execute("SELECT count(*) FROM %s" % table).fetchone()[0]
        assert a == b, "%s: source has %d rows, dump has %d" % (table, a, b)
        cols = [r[1] for r in src.execute("PRAGMA table_info(%s)" % table)]
        order = ", ".join(cols)
        sa = src.execute("SELECT %s FROM %s ORDER BY %s" % (order, table, order))
        sb = dst.execute("SELECT %s FROM %s ORDER BY %s" % (order, table, order))
        n = 0
        for ra, rb in zip(sa, sb):
            assert ra == rb, "%s row mismatch:\n  src %r\n  dump %r" % (table, ra, rb)
            n += 1
        print("PASS  %s: %d rows identical" % (table, n))
    print("ALL CHECKS PASS")


if __name__ == "__main__":
    if not os.path.exists(DB):
        sys.exit("no database at %s; run pipeline/run_all.py first" % DB)
    if "--check" in sys.argv:
        if not os.path.exists(OUT):
            sys.exit("no dump at %s; run without --check first" % OUT)
        check()
    else:
        dump()
